### ISSUE TITLE
pip installation failed

### ISSUE THREAD

**Issue by DBFZmdotzauer** [LeMoussel/pydbhub#3]
I've struggle to install pydbhub via pip.
The installation seem to be finished, but i was't able to import pydbhub, and pydbhub wan't shown in the package list using `pip list`.

@ Python 3.7.9
```
>>>pip install pydbhub --user
Collecting pydbhub
  Downloading pydbhub-0.0.3-py37-none-any.whl (3.0 kB)
Collecting rich
  Downloading rich-10.15.2-py3-none-any.whl (214 kB)
Requirement already satisfied: requests in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from pydbhub) (2.25.1)
Requirement already satisfied: python-dateutil in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from pydbhub) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from python-dateutil->pydbhub) (1.14.0)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from requests->pydbhub) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from requests->pydbhub) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from requests->pydbhub) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from requests->pydbhub) (2021.5.30)
Collecting colorama<0.5.0,>=0.4.0
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting typing-extensions<5.0,>=3.7.4
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting pygments<3.0.0,>=2.6.0
  Downloading Pygments-2.10.0-py3-none-any.whl (1.0 MB)
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Installing collected packages: typing-extensions, pygments, commonmark, colorama, rich, pydbhub
Successfully installed colorama-0.4.4 commonmark-0.9.1 pydbhub-0.0.3 pygments-2.10.0 rich-10.15.2 typing-extensions-4.0.1
```

But can't access the library:

```
>>> import pydbhub
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'pydbhub'
```

And also I've found just a folder "pydbhub-0.0.3.dist-info" but no package folder.

If any further information is needed I'll try to serve it.
Thanks in advance,
Martin

**Comment by LeMoussel** [comment]
What is the result if you install directly from Git?

**Comment by DBFZmdotzauer** [comment]
Thanks for the fast reply, but unfortunately the result keep the same :-/

```
>>> pip install --upgrade git+git://github.com/LeMoussel/pydbhub.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+git://github.com/LeMoussel/pydbhub.git
  Cloning git://github.com/LeMoussel/pydbhub.git to c:\users\mdotza~1\appdata\local\temp\pip-req-build-1tltb6g5
  Running command git clone --filter=blob:none -q git://github.com/LeMoussel/pydbhub.git 'C:\Users\MDOTZA~1\AppData\Local\Temp\pip-req-build-1tltb6g5'
  Resolved git://github.com/LeMoussel/pydbhub.git to commit 501ea2c0ec7785bc06a38961a1366c3c04d7fabd
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: requests in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from pydbhub==0.0.3) (2.25.1)
Requirement already satisfied: python_dateutil in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from pydbhub==0.0.3) (2.8.1)
Requirement already satisfied: rich in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from pydbhub==0.0.3) (10.15.2)
Requirement already satisfied: six>=1.5 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from python_dateutil->pydbhub==0.0.3) (1.14.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from requests->pydbhub==0.0.3) (2021.5.30)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from requests->pydbhub==0.0.3) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from requests->pydbhub==0.0.3) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from requests->pydbhub==0.0.3) (1.26.4)
Requirement already satisfied: typing-extensions<5.0,>=3.7.4 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from rich->pydbhub==0.0.3) (4.0.1)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from rich->pydbhub==0.0.3) (0.9.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from rich->pydbhub==0.0.3) (0.4.4)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\mdotzauer\appdata\roaming\python\python37\site-packages (from rich->pydbhub==0.0.3) (2.10.0)


>>> import pydbhub
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'pydbhub'
```
 
best,
Martin

**Comment by LeMoussel** [comment]
Strange. This seems to be a concern of your Python environment.

**Comment by DBFZmdotzauer** [comment]
May be. I'll try to update to the latest version of python 3.7. 
But many thanks for your feedback.
